### ISSUE TITLE
Different frame difference

### ISSUE THREAD

**Issue by saruvora** [StanfordASL/Trajectron#6]
Hi, @BorisIvanovic ,
I was working with the [format data](https://github.com/StanfordASL/Trajectron/blob/master/sgan-dataset/format_data.py), and noticed frame_diff, I want to know what if I have different frame differences? I have a dataset where the same pedestrian exits and enters the scene after some time. How should I deal with that?

**Comment by BorisIvanovic** [comment]
Hi @saruvora ,

`frame_diff` refers to if you have annotations only every N frames, so that the data formatting script renames them to be sequential numbers. If you have different frame differences, then you might want to opt for your own frame relabeling scheme (creating a dict from one set of integers to another, for example).

The way I've currently set up the code is that, even if you know the same pedestrian exits and later re-enters the scene, it is better to assign that re-entry a different pedestrian label. Having a bunch of zeros following a trajectory and then preceding another will not serve the model well in terms of prediction. It's better to have the model remove that node from its graph and recreate it when the pedestrian re-enters.

Hope this helps!
