### ISSUE TITLE
Parameters in format_data

### ISSUE THREAD

**Issue by saruvora** [StanfordASL/Trajectron#9]
Hi can you explain a bit about the parameters in [format_data.py](https://github.com/StanfordASL/Trajectron/blob/master/sgan-dataset/format_data.py) 

`
desired_max_time = 100
pred_indices = [2, 3]
state_dim = 6
frame_diff = 10
desired_frame_diff = 1 
`
what do they mean ?

**Comment by BorisIvanovic** [comment]
`desired_max_time` is how many timesteps you want per scene (the format_data script first chops the data up into smaller, constant-length scenes).

`pred_indices` is the indices of the state that you want the model to predict ([2, 3] because we want the model to predict velocity in the x and y direction which are at index 2 and 3 in the state vector). 

`state_dim` is how many dimensions the state has (6 because our state is [x, y, vx, vy, ax, ay])

`frame_diff` is how many frames there are between each position annotation (in the pedestrian datasets, this is 10)

`desired_frame_diff` is how many frames you wish there to be between each position annotation. So what happens is the data might be incrementing from 780 -> 790 -> 800 -> 810 -> etc, but we really want it to be 78 -> 79 -> 80 -> 81 -> etc. This is what this and the previous parameter set.

**Comment by saruvora** [comment]
> `desired_max_time` is how many timesteps you want per scene (the format_data script first chops the data up into smaller, constant-length scenes).
> 
> `pred_indices` is the indices of the state that you want the model to predict ([2, 3] because we want the model to predict velocity in the x and y direction which are at index 2 and 3 in the state vector).
> 
> `state_dim` is how many dimensions the state has (6 because our state is [x, y, vx, vy, ax, ay])
> 
> `frame_diff` is how many frames there are between each position annotation (in the pedestrian datasets, this is 10)
> 
> `desired_frame_diff` is how many frames you wish there to be between each position annotation. So what happens is the data might be incrementing from 780 -> 790 -> 800 -> 810 -> etc, but we really want it to be 78 -> 79 -> 80 -> 81 -> etc. This is what this and the previous parameter set.

Hi @BorisIvanovic thank you for the response I am still not clear with ´desired_max_time` if I want to consider all my data as it is should it be equal to the max time of the a pedestrian in the entire dataset ? 

And do you also have a way to convert the data back to SGAN format from Trajectron format ?

**Comment by BorisIvanovic** [comment]
You're still considering all of the data, it just takes the data from a shape of (1, 13000) to a shape of (130, 100). It doesn't have to be equal to the maximum time of a pedestrian in the entire dataset, it doesn't clip any data, just reshapes it.

Unfortunately, I do not have a way to convert the data back to SGAN format. I do some matching of data when I evaluate the models side-by-side in [evaluate_alongside_sgan.py](https://github.com/StanfordASL/Trajectron/blob/master/code/evaluate_alongside_sgan.py), but nothing more explicit than that.

**Comment by saruvora** [comment]
> You're still considering all of the data, it just takes the data from a shape of (1, 13000) to a shape of (130, 100). It doesn't have to be equal to the maximum time of a pedestrian in the entire dataset, it doesn't clip any data, just reshapes it.
> 
> Unfortunately, I do not have a way to convert the data back to SGAN format. I do some matching of data when I evaluate the models side-by-side in [evaluate_alongside_sgan.py](https://github.com/StanfordASL/Trajectron/blob/master/code/evaluate_alongside_sgan.py), but nothing more explicit than that.

Hi thank you for the information :) i tried that and then my number of pedestrians reduced but their shape increased so now I know what was happening. 

I habe two more questions:
1. Do you use sliding window approach to read the pedestrians ? For example is the trajectory is from [0, 21] so you first read [0, 19] then [1, 20] and finally [2, 21] ? 

2. In the test_online.py you predict the future trajectory only for a certain number of pedestrians right using only one set of positions of each of the pedestrians present in the scene. I want to use it to evaluate all the data from all the pedestrians that i have so how can i do that using the data Id ?

**Comment by BorisIvanovic** [comment]
1. This is something you can do if you want, but as of now it would just take in [0, 21] (since the model is recurrent in its input, there's no need to limit it, unless you want to maintain a fixed temporal window as input).

2. In test_online.py, it starts from some timestep (up to you what that is) and then as time advances you can incrementally increase the number of pedestrians as they appear in the data since the model will inherently scale up to accommodate them. There's no need to do any desired_max_time if you don't want to on the test dataset, since the model doesn't care about max time as it simply works from streaming data.

**Comment by saruvora** [comment]
> 1. This is something you can do if you want, but as of now it would just take in [0, 21] (since the model is recurrent in its input, there's no need to limit it, unless you want to maintain a fixed temporal window as input).
> 2. In test_online.py, it starts from some timestep (up to you what that is) and then as time advances you can incrementally increase the number of pedestrians as they appear in the data since the model will inherently scale up to accommodate them. There's no need to do any `desired_max_time` if you don't want to on the test dataset, since the model doesn't care about max time as it simply works from streaming data. This means you can simply feed in data as you wish (via the agent positions at each time) and the model can produce predictions also as you wish (either every timestep or only on certain timesteps).

Hi @BorisIvanovic thank you for the information. 

I would like to know if you have some documentation for the data_set that you create? I am a lot confused about it. 
Do you generate the values for each scene for all the pedestrians? 
I am still not able to understand why the number of pedestrians decreases with desired_max_time. Does it still consider data from all the pedestrians or not? 
If I want to plot all the pedestrians then just plotting the data_id for all the entire dataset is enough ?
